remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-remote-theme
toc:
  enabled: true
  h_min: 1
  h_max: 3
collections:
  pages:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext
  others:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext